### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by jleroy** [pydio/pydio-booster#3]
I've found multiple errors in the Pydio Booster [install guide](https://pydio.com/en/docs/v7/install-pydio-booster):
 - The link "DOWNLOAD PYDIO BOOSTER" point to version 0.8.6, not to the latest version available (1.0.1). Please consider create a "latest" symlink that always redirect to the last version.
 - After following all the steps described in this guide, I can't get Pydio Booster to work. I'm getting the folloxing error:
```
# /usr/local/bin/pydio-booster -c /etc/pydio/booster.conf 
flag provided but not defined: -c
```

**Comment by fanningert** [comment]
replace `-c` with `-config`

**Comment by cdujeu** [comment]
FYI, you are more than welcome submitting changes on https://github.com/pydio/pydio-doc-admin-guide/blob/v7/getting-started/3_installing_pydio_booster.md (see various branches corresponding to the various docs). The how-to's are also available there.
